### ISSUE TITLE
Suppport random when do_sample

### ISSUE THREAD

**Issue by Hukongtao** [NVIDIA/TensorRT-LLM#1000]
When we do sampling, the output seems to be the same every time.

If a random seed is set before each sampling, the results will vary with the random seed.
https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/runtime/generation.py#L353

But I think that the default random seed is None, so the sampling results should be different each time by default?

Related questions：https://github.com/NVIDIA/TensorRT-LLM/issues/128

**Comment by byshiue** [comment]
The program will initialize its random table by the passed random seed every time. When you don't pass random seed, it will initalize the random table by random seed 0 every time, and generate same results. This is expected behavior. 

If you want to generate different results every time, you should pass different random seed every time.
