### ISSUE TITLE
[Feature Request] Using TRTLLMEncDecModel from the TensorRT-LLM python package

### ISSUE THREAD

**Issue by guilherme-pombo** [NVIDIA/TensorRT-LLM#1082]
Hello, thank you for this great project! Currently when converting a T5 model to TRT format, if I then want to use it from another codebase I need to clone this repository and access the class definition from examples/enc_dec, as 

`from examples.enc_dec import TRTLLMEncDecModel`

this is not ideal for many reasons but above all it makes it harder to use TensorRT-LLM from other projects and causes unecessary attrition. Would it be possible to refactor the code in such a way that after I pip install TensorRT-LLM I can import that class as follows:

`from tensorrt_llm.enc_dec import TRTLLMEncDecModel`

or something of a similar nature? I reckon this could really help increase TensorRT-LLMs adoption as well. Thank you very much.

**Comment by symphonylyh** [comment]
Hi @guilherme-pombo , thanks for initiating this discussion!

Since we did abstraction for a generic EncDecModel structure, you can see that (1) we put the subcomponents as the pip-installable classes, e.g., we can now do `from tensorrt_llm.models import EncoderModel`, `from tensorrt_llm.models import DecoderModel`, `from tensorrt_llm.models import WhisperEncoder` (2) we then put together the `TRTLLMEncDecModel` as a runtime wrapper to run the engines, because what it does is just load and run the encoder & decoder engines, without holding any model definition code.

From the description of your pain point above, I was wondering if you can just copy the `examples/enc_dec/run.py` file and modify it to fit your application -- this is what the `examples` folder intends to do, i.e., provide a demo code that the users can tailor to their use cases.

Does this work for you?

**Comment by guilherme-pombo** [comment]
Hello @symphonylyh that works for me and it's what I have been doing, however, I was wondering if it would also be possible to provide a generic TRTLLMEncDecModel() wrapper, as to avoid having to copy code over from the examples folder and adding technical debt to internal codebases? Or is this hard because it won't necessarily generalise to all Encoder-Decoder models?
