### ISSUE TITLE
failed to build tensorrt_llm wheel on windows since no msvc version of executor found

### ISSUE THREAD

**Issue by terryaic** [NVIDIA/TensorRT-LLM#1209]
reported failed for C:/workspace/TensorRT-LLM/cpp/tensorrt_llm/executor/x86_64-windows-msvc/tensorrt_llm_executor_static.lib

this issue maybe related the the one I created before #1161

**Comment by tp5uiuc** [comment]
Hi @terryaic, currently windows build is only supported on the `rel` branch (which is thoroughly tested, and was updated a couple of days ago) rather than the `main` branch (which contains latest and greatest but is untested). Only windows build on `main` requires access to the executor library. Can you please rebuild on `rel` instead of `main`?

**Comment by terryaic** [comment]
thanks for the reply, but I indeed need to build it in main stream.

**Comment by tp5uiuc** [comment]
Ok, currently wheel building on `main` is WIP and unsupported. Marking this as won't fix for now. Will let you know if the situation changes anytime in the future.
