### ISSUE TITLE
  How to establish a Flask application within the built Docker container, with the same IP address as the host (server address)

### ISSUE THREAD

**Issue by bjleah** [NVIDIA/TensorRT-LLM#131]
After running the Docker using the "make - C Docker run" command, I created a Flask program inside the Docker container. How can I modify the makefile or modify the startup method to make the Flask application have the same IP as the host.

**Comment by uppalutkarsh** [comment]
Assuming you have created the TRT-LLM image, you can launch the container using `docker run` command too instead of `make -C docker run` and map the ports as per your requirement using `-p` flag. 

Also, you can explore [TRT-LLM backend](https://github.com/triton-inference-server/tensorrtllm_backend) in Triton Inference Server for serving.

**Comment by bjleah** [comment]
> Assuming you have created the TRT-LLM image, you can launch the container using `docker run` command too instead of `make -C docker run` and map the ports as per your requirement using `-p` flag.
> 
> Also, you can explore [TRT-LLM backend](https://github.com/triton-inference-server/tensorrtllm_backend) in Triton Inference Server for serving.

Thank you very much, I will give it a try in a moment.

**Comment by jdemouth-nvidia** [comment]
Marking as closed for now - reopen if needed.
