### ISSUE TITLE
How can I get the performance across a suite of popular benchmarks like code/Commonsense Reasoning 

### ISSUE THREAD

**Issue by taoxunqiang** [NVIDIA/TensorRT-LLM#161]
Thanks for such a great job. 
I have a question.
How to compare the performance of the models before and after quantization across a suite of popular benchmarks like code/Commonsense Reasoning Reasoning listed on Table 3 of Llama2 paper.

Thank you in advance.

**Comment by juney-nvidia** [comment]
@taoxunqiang  to confirm my understanding firstly, "the performance" here means the accuracy rather than the latency or throughput, correct?  If so, a DIY approach is to refer the existing [summarize.py](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/summarize.py) to add the related accuracy measurement logic by yourself.

June

**Comment by taoxunqiang** [comment]
@juney-nvidia  
Your understanding is right.
Thanks for the quick reply.
