### ISSUE TITLE
[Question] Dockerfile to run inference with TensorRT-LLM compiled files

### ISSUE THREAD

**Issue by snassimr** [NVIDIA/TensorRT-LLM#1710]
Hi ,

I am searching for Dockerfile that given rank0.engine and config.json files would expose inference server . Any link for reference ?

Thanks

**Comment by hijkzzz** [comment]
Could you mount the engine directory into the docker container?

**Comment by snassimr** [comment]
Yep . To make clear : I am searching Dockerfile that would contain all dependencies to run inference with rank0.engine and config.json (outputs of compiling with TensorRT-LLM).

**Comment by hijkzzz** [comment]
Triton? https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver

**Comment by snassimr** [comment]
Yep . It could help , but it's too big . It has been discussed her https://github.com/NVIDIA/TensorRT-LLM/issues/1704 . What your plan to create smaller image ?

**Comment by byshiue** [comment]
We will discuss that. Because using pip to install tensorrt-llm often leads to version mismatch before TRT-LLM supports backward compability, we determine to install the tensorrt-llm python package in the tritonserver docker image since the 24.04 docker image and lead to larger docker image size. 

Currently, nvcr.io/nvidia/tritonserver:24.05-trtllm-python-py3 is the only choice.
