### ISSUE TITLE
Question on how to perform cross-attention with FMHA kernel

### ISSUE THREAD

**Issue by Ashwin-Ramesh2607** [NVIDIA/TensorRT-LLM#1956]
I am interested in performing multimodal cross-attention. I don't see issues in performing self-attention in encoder since i can use the `BertAttention` plugin. However, cross-attention would have `query` from one modality (with seq_len as `x` and `key/value` from another modality (with seq_len as `y`). It's possible that the 2 modalities have different sequence lengths.

Can I please get some guidance on how to accomplish this?
1. Is there a way to perform FMHA when `q` and `kv` have different `seq_len`. Afaik, the `BertAttention` plugin switches to non-FMHA path for this.
2. Can I modify the plugin or hack around this to ensure I use `FMHA`?

**Comment by PerkzZheng** [comment]
The paged context fmha has been supported in the main branch for cross-attention. 
see https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/plugins/gptAttentionCommon/gptAttentionCommon.cpp#L1980-L1985,
and https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/plugins/gptAttentionCommon/gptAttentionCommon.cpp#L1216-L1358.

The fmha runner also supports contiguous q and kv input for cross-attention, but it hasn't been enabled in trtllm because of the mismatching contiguous kv cache layout.  You can also give it a try if your kv input has layout similar like q without paddings, which is like [numKvTokens, 2, numHeads, headSize].
