### ISSUE TITLE
Question: node_sharding_weight / edge_resharding_weight

### ISSUE THREAD

**Issue by saeyoonoh** [NVIDIA/TensorRT-LLM#1996]
Hi, I am trying to understand the underlying code for auto_parallel. 

the solver.py inside auto_parallel uses node_sharding_weight and edge_resharding_weight to add weight coefficients to 
each node communication cost and edge resharding costs. 

the node_sharding_weight and node_resharding_weight gets incremented as follows: 
```       
for layer_name in layer_mapping.values():
   node = self.get_node(layer_name)
   node.sharding_weight += 1
   node.resharding_weight += 1
```

May I ask the purpose of applying these weights? 

I believe that such work is important and appreciate your help and the works. 
Thanks :)

**Comment by yuxianq** [comment]
@saeyoonoh Because we simplify the graph before passing it to the solver (see tensorrt_llm/auto_parallel/simplifier.py). LLM usually contains a lot of repeated blocks, we can simplify the model by elimating most blocks (e.g. from N blocks to 2 blocks) to reduce computation cost of the solver. To correctly estimate the cost of each node/edge, we assign a `sharding_weight` for each of them to make the total cost equal to the original graph before simplified. For example, if the simplified graph contains 2 blocks, the `sharding_weight` of nodes/edges in one block should be 1, and those in another block should be N-1, which simulates the original N-block case. The `layer_mapping` records the mapping from the elimated layers to the reserved layers.

**Comment by saeyoonoh** [comment]
Thanks for the detailed answer. It helps me a lot.
