### ISSUE TITLE
Wasteful computations in cross attention?

### ISSUE THREAD

**Issue by thefacetakt** [NVIDIA/TensorRT-LLM#2026]
As far as i understand, when using cross_attention we first compute `qkv = self.qkv(hidden_states)`, and then `cross_qkv = self.qkv(encoder_output)`. But later only `q` from `qkv` is used, and only `kv` from `cross_qkv` is used.

Seems like wasteful computation. Perhaps, there should be two matrices: q and kv.
(This will also improve quantization a bit, since there will be separate scales)

**Comment by QiJune** [comment]
@symphonylyh  Could you please take a look? Thanks

**Comment by symphonylyh** [comment]
@thefacetakt correct. this is to be more consistent with the fused QKV gemm used in all models, but indeed will bring some redundant computation.

However, I think it won't be very significant in the entire computation:

1. 1st qkv gemm on hidden states: this is arguably redundant. But since each time the length of hidden states is 1, the cost of this redundant computation might not be huge, i.e. [1, H] * [H, 3X] vs [1, H] * [H, X] 
2. 2nd qkv gemm on encoder output: this would be less important, as this gemm is done only once during the entire run. After that, the data is saved in cross kv cache and no long need to use encoder output.

Do you agree?

We can still investigate on (1), to see whether it's critical enough. Otherwise, maybe keeping consistent with other models with <1% slow down is acceptable.

**Comment by nv-guomingz** [comment]
Hi @thefacetakt  please reopen it if needed.
