### ISSUE TITLE
How can I use flan-t5-base?

### ISSUE THREAD

**Issue by shainisan** [NVIDIA/TensorRT-LLM#251]
I tried to follow the logic [from here](https://github.com/NVIDIA/TensorRT-LLM/issues/127) but I'm not able to load and use the google/flan-t5-base

I'll appreciate your help with this.

Thanks.

**Comment by symphonylyh** [comment]
Hi we're working on Flan-T5, there are changes needed in weight loading and model definition to enabled flan-T5's gated activation. We'll ping this thread once it's done

**Comment by nish996** [comment]
Hi @symphonylyh ,
Any idea on when the flan t5 models would be supported?

**Comment by symphonylyh** [comment]
Hi @shainisan @nish996 , more general T5 and Flan-T5 support has been done and scheduled for TRT-LLM's 0.6.0 monthly release soon. Please stay tuned.

**Comment by symphonylyh** [comment]
@shainisan @nish996 , actually it has been released to dev branch (i.e., `main`) earlier! please check: https://github.com/NVIDIA/TensorRT-LLM/discussions/424.

**Comment by shainisan** [comment]
Amazing! Thank you!

**Comment by shainisan** [comment]
@symphonylyh can you please explain what should be done in order to use the new feature? 
Should I change the branch to main and rebuild the docker? Or something else?
Thanks!

**Comment by symphonylyh** [comment]
> @symphonylyh can you please explain what should be done in order to use the new feature? Should I change the branch to main and rebuild the docker? Or something else? Thanks!

Generally speaking, the most stable way to use a new version (i.e., new commits pushed to the dev `main` branch OR a major release with `release/x.x.x`) is to redo the steps in the [docs/installation.md](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md): (1) rebuild docker images (2) inside new docker container, rebuild TRT-LLM c++ source code and install python wheel.

For major release, it's likely the docker image has to be rebuilt (which doesn't take very long) because we may have updated the base environment and submodules. For most update commits to the dev `main` branch, you can usually use the same docker you have, but need to re-run the cpp build & wheel install commands. I would recommend you try (2) first; if it doesn't work, do (1) & (2).
