### ISSUE TITLE
Possible to compile quantized llama7B for A10G with 22.7 GB vRAM and 30GB RAM (g5.2xlarge)?

### ISSUE THREAD

**Issue by Bhuvanesh09** [NVIDIA/TensorRT-LLM#257]
A quantized model compiled on A100 doesn't work in A10G even though they are both based on Ampere's architecture. 
Is there any possible method to load and compile a quantized llama model on A10G given the memory limitations? In vanilla transformers, we can load llama7b into A10G by specifying the datatype as `torch.float16`. But even with quantization and datatype as fp16, tensor-rt-llm seems to loads the entire model into the RAM before conversion which leads to OOM.
Is there any recommended way to circumvent this issue?

**Comment by cody-moveworks** [comment]
I also ran into this same issue. I ended up upgrading to g5.12xlarge instance because I was also testing out using larger models, but you may be able to get by with a g5.4xlarge or maybe g5.8xlarge.

**Comment by harryjulian** [comment]
@Bhuvanesh09 for Falcon-7b, I made a 32GB [swapfile](https://itsfoss.com/create-swap-file-linux/) on a `g5.2xlarge` which just about allowed me to compile the model -- peak RAM usage was just under 60GB.

**Comment by litaotju** [comment]
>I made a 32GB [swapfile](https://itsfoss.com/create-swap-file-linux/) on a g5.2xlarge which just about allowed me to compile the model -- peak RAM usage was just under 60GB.
 
@Bhuvanesh09 @harryjulian so here you are talking about OOM in CPU RAM right? Not GPU memory.
Could you help to provide more detailed information on these, so we can help to debug?
1. The TRT-LLM commands
2. The TRT-LLM version, and the container information

**Comment by shixianc** [comment]
I'm seeing the same RAM OOM issue for Falcon-7B model. 
```

python build.py --model_dir ./model \
                --dtype float16 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --paged_kv_cache \
                --max_batch_size 2 \
                --max_input_len 16 \
                --max_output_len 32 \
                --output_dir falcon/7b-instruct/trt_engines/bf16/1-gpu/ \
                --world_size 1
```

I even tried with much smaller batch size and input/output lengths. The RAM usage I'm seeing around 60-70 GiB, so we'll need at least a g5.8xlarge.

**Comment by litaotju** [comment]
We recently added a --load-by-shard parameter for build.py, pls see https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/falcon/build.py#L235 which can decreate the memory size to load model. Pls try if this works.

In theory, the process could use about 2x + weights size of cpu memory. 1x is the TRT-LLM module object, and 1x is the built TRT engine  (since the weights needs to be inside the engine, TRT can tune the weights layout/precisions). Considering some constant folding or transformation optimization, the CPU memory peak could be 3x+.


The runtime could have less CPU memory usage than build time, since only the TRT engine has CPU memory weights, pls try to find more CPU memory node for build.
