### ISSUE TITLE
ptuning support feature

### ISSUE THREAD

**Issue by jonnyhe** [NVIDIA/TensorRT-LLM#295]
Is there any plan to support Ptuning?
Such as Ptuning V2 for Chatglm?

**Comment by ncomly-nvidia** [comment]
Hi @jonnyhe TRT-LLM does support some models with prompt-tuning, however, it is all expose through [NeMo Framework](https://developer.nvidia.com/nemo).
What FW are doing your prompt tuning in? In general we recommend to use NeMo for model customizations / fine-tuning since includes TRT-LLM as default when you go to deploy on inference.

**Comment by jonnyhe** [comment]
O.K. The ptuning for GLM is a little bit different. It is P-tuning-v2 and is differently with P-tuning. 
For the Nemo, it is mainly for P-tuning.
For the detailed information, you can see the following. (https://github.com/THUDM/P-tuning-v2)

**Comment by nv-guomingz** [comment]
Please try our latest code base and feel free to reopen this ticket if needed.
