### ISSUE TITLE
Provide an interface similar to OpenAI API

### ISSUE THREAD

**Issue by Pevernow** [NVIDIA/TensorRT-LLM#334]
Could you please provide a simple interface similar to OpenAI API?

**Comment by juney-nvidia** [comment]
@Pevernow 
Can you elaborate more about your request?
Thanks
June

**Comment by Pevernow** [comment]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/29888010/796adf68-ccda-4c0a-a60c-6dd5247c2007)
The most basic thing is just a simple chat/completions function similar to OpenAI.

The purpose is to facilitate access to existing applications that use the chatgpt API.

Currently, many open-source LLM projects have implemented this feature, such as the famous oobabooga/text generation webui

**Comment by merrymercy** [comment]
Users want something like this https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md, so they can switch their apps from OpenAI models to TRT-LLM models easily without code change.

**Comment by Pevernow** [comment]
@juney-nvidia Please take a look here, thank you

**Comment by gesanqiu** [comment]
Right now Python API still have a lot of issues to be fixed, I encapsulated one OpenAI API, but met #283, so you still need use C++ runtime, which means you need Triton. Spent weeks on TRT-LLM, it difficult to develop on python runtime.

@juney-nvidia What's the position of TRT-LLM's Python runime? I mean, python is easier than C++, and batch manager doesn't open source right now. Most developors may not use Triton since they won't meet that large commercial demand.

**Comment by chrjxj** [comment]
mark

**Comment by juney-nvidia** [comment]
Sorry for replying late due to being trapped by other things.

> Users want something like this https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md, so they can switch their apps from OpenAI models to TRT-LLM models easily without code change.

@Pevernow @merrymercy  well received, will discuss with prod about this. @ncomly-nvidia  for vis. 

> What's the position of TRT-LLM's Python runime? I mean, python is easier than C++, and batch manager doesn't open source right now. Most developors may not use Triton since they won't meet that large commercial demand.

@gesanqiu we have already released the [Python binding of C++ runtime](https://github.com/NVIDIA/TensorRT-LLM/tree/main/cpp/tensorrt_llm/pybind), including batch manager, does this fulfill your requirement here?

**Comment by binarycrayon** [comment]
vote up, monitoring

**Comment by binarycrayon** [comment]
More info about openai chat completion API spec here
https://github.com/openai/openai-openapi/tree/master

**Comment by whk6688** [comment]
i need it too

**Comment by LMarino1** [comment]
+1 for OpenAI API support

**Comment by Mary-Sam** [comment]
+1 for OpenAI API support

**Comment by mynameiskeen** [comment]
+1 for OpenAI API support, it's been 9 months since the pr requested :(

**Comment by palindsay** [comment]
+1 OpenApi support

**Comment by nstl-zyb** [comment]
+1

**Comment by wertyac** [comment]
+1 for openai api support。

**Comment by Alireza3242** [comment]
+1 for openai api support

**Comment by mohankrishna225** [comment]
+1 for openai api support

**Comment by viningz** [comment]
+1 for openai api support

**Comment by Wonder-donbury** [comment]
+1 for openai api support

**Comment by mmoskal** [comment]
You may be interested in [llgtrt](https://github.com/guidance-ai/llgtrt) - it's a Rust implementation of Openai compatible server based on trt llm with structured output.

**Comment by nv-guomingz** [comment]
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/apps#openai-api

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
