### ISSUE TITLE
conflict with huggingface chatglm2-6b

### ISSUE THREAD

**Issue by liquanfeng** [NVIDIA/TensorRT-LLM#476]
https://github.com/NVIDIA/TensorRT-LLM/blob/6837c8141acd036b8884330f4eadb50e097163f7/tensorrt_llm/models/chatglm2_6b/model.py#L368

**Comment by liquanfeng** [comment]
Hi, there is a line miss with [chatglm2-6b  in huggingface](https://huggingface.co/THUDM/chatglm2-6b/blob/7fabe56db91e085c9c027f56f1c654d137bdba40/modeling_chatglm.py#L559). So  I am confused why not use `residual` to be add?

**Comment by jdemouth-nvidia** [comment]
I’m going to ask our ChatGLM expert to take a look. Thanks.

**Comment by wili-65535** [comment]
Thank you for your notice about this! @liquanfeng 
As you said, here we should use `residual` (rather than `hidden_state`) to add to keep semantics consistency. But for original ChatGLM2-6B model, the switch "apply_residual_connection_post_layernorm" is always False (https://huggingface.co/THUDM/chatglm2-6b/blob/7fabe56db91e085c9c027f56f1c654d137bdba40/config.json#L17) so no error raises with "layernorm_input = hidden_states + attention_output" here.
In addition, this error has been fixed in the newer version of ChatGLMX-6B models. (https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/chatglm/model.py#L293C17-L293C17)
