### ISSUE TITLE
How can i build wheel if my tensorrt is installed using TRT

### ISSUE THREAD

**Issue by littletomatodonkey** [NVIDIA/TensorRT-LLM#477]
Hi, thanks for you great job!

I want to install tensor_llm using [the doc](./docs/source/installation.md), but it seems that i have to download tensorrt source file firstly. However i install tensorrt using pip, which is as follows.

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/14270174/c460f930-2691-4035-894b-4f9c883482e2)

So how can i build wheel in this case(trt is installed by pypi), thank you !

**Comment by Shixiaowei02** [comment]
Hi @littletomatodonkey , thanks for your interest in us! You just need to run `pip install tensorrt==9.1.0.post12.dev4`. BTW, the installation of TensorRT-LLM needs [the distribution release of TensorRT](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docker/common/install_tensorrt.sh#L78) instead of source files. So the two methods above are equivalent.
