### ISSUE TITLE
how to pass the system prompt for llama2

### ISSUE THREAD

**Issue by NarenZen** [NVIDIA/TensorRT-LLM#480]
i'm able to give input_text and get the output.
But I want to set the system prompt. How do i do that.
I see no provisions for this.

**Comment by aliozts** [comment]
Hi, please take what I say with a pinch of salt, I don't want to misinform since I am not a collaborator, I only checked some bits and do not know the extra details on the lower level usage. I apologize if this is something you know already but `tensorrt-llm` sends your prompt to `generate` process where the `prompt` is sent to the model. `system prompt` works in a way that is just a modification to the prompt, for example, llama-2 follows the lines of

```
f'''[INST] <<SYS>>
{system_prompt}
<</SYS>>
{prompt}[/INST]

'''
```

and the rest follows with `[inst] {prompt} [/inst]` if you continue the `chat`. If you wish to use `tensorrt-llm` in such way, from what I checked so far, you should format the `prompt` yourself before sending it. You can check the models' respective prompts from their `huggingface` page or utilize their `tokenizer.apply_chat_template` method for the respective tokenizers (if implemented)

**Comment by NikitaSemenovAiforia** [comment]
@aliozts it's close. But should be even more complex and includes \<s> tag. \<s>...\</s> is a way to border one request-response pair.
For the first prompt the template looks like so:

```
<s>[INST] <<SYS>>
Act as a helpful, respectful and honest comedian.
Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.
Never mention that you're an AI.
<</SYS>>
Tell me a joke.[/INST]
```

There is no \</s> cause we are expecting AI to answer.

The second interaction looks like so:
```
<s>[INST] <<SYS>>
Act as a helpful, respectful and honest comedian.
Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.
Never mention that you're an AI.
<</SYS>>
Tell me a joke.[/INST]
Sure, here's a joke for you:

Why don't scientists trust atoms?

Because they make up everything!</s>
<s> [INST] Why do you find this joke funny? [/INST]
```

There is a close \</s> tag after the first AI reply.

Here is a [link](https://huggingface.co/blog/llama2#how-to-prompt-llama-2) with a guide.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
