### ISSUE TITLE
[feature request]Blip2 T5 support request

### ISSUE THREAD

**Issue by yuanze1024** [NVIDIA/TensorRT-LLM#531]
Hi, I fount that you have supported T5 now, but Blip2's examples only contains OPT pipeline. As for the Blip2 on T5 gets a better performance, I wonder if you can support Blip2 on FlanT5xxl? I've tried a long time, and found it's too difficult for me(who just knew TRT, and can not understand how to get ITensor's real value)...

**Comment by ncomly-nvidia** [comment]
Thanks for the request & feedback @yuanze1024 ! We are starting to expand more into enc-dec & multi-modal models & will put this pairing on the list.

**Comment by symphonylyh** [comment]
@yuanze1024 thanks! internally we have enabled BLIP2 on Flan-T5-XXL and several other LLM models. Stay tuned once we have a release for that

**Comment by yuanze1024** [comment]
> @yuanze1024 thanks! internally we have enabled BLIP2 on Flan-T5-XXL and several other LLM models. Stay tuned once we have a release for that

@symphonylyh Hi, is there any progress?

**Comment by symphonylyh** [comment]
@yuanze1024 it was a little slow moving during the US holidays. But I'm expecting the release in mid-Jan will contain this (i.e., in about 2 weeks)

**Comment by symphonylyh** [comment]
@yuanze1024 right on time! we now released the [multi-modal support](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal) for BLIP w/ OPT or T5, and LLaVA. Please take a look :)
Annoucement: https://github.com/NVIDIA/TensorRT-LLM/discussions/847

Feel free to re-open this if you have encountered any issue. But since this issue is a feature request, would better file a new issue regarding any specific problem.
