### ISSUE TITLE
Best way to deploy/test LLM models on TensorRT-LLM for production

### ISSUE THREAD

**Issue by amir1m** [NVIDIA/TensorRT-LLM#581]
Hello,
I am using a fine tuned open source LLM and it works great in the Docker after following the instructions to build TensorRT-LLM. 

However, after building the wheel install package I am not able to install it on Ubuntu VM, fails at TensorRT installation step.

Can someone please help with the following:
- What is the recommended way to deploy using TensorRT-LLM?
- If its using Docker/container are there any instructions available to build custom image(with custom model serving logic) on top the one provided by TensorRT-LLM?

Thanks.

**Comment by juney-nvidia** [comment]
@amir1m 

Hi,

Which Ubuntu version are you using to install TensorRT-LLM pip package.
And recording to the _"recommended way to deploy using TensorRT-LLM"_, I want to understand more of this request. Do you mean our suggestion as to how to install TensorRT-LLM in different environments? Or how to set up a LLM service based on TensorRT-LLM?  

_"If its using Docker/container are there any instructions available to build custom image(with custom model serving logic) on top the one provided by TensorRT-LLM"_
Since there are already provided docker file in the github, I think you can just use them as the starting point to add your own docker customization logic. 

Hoping this can be helpful to you.

Thanks
June

**Comment by amir1m** [comment]
Hi @juney-nvidia ,
I think we need to rebuild the Docker image if we need any more python packages, custom inference code and rebuild it. I was using incorrect command to re-build it. 

Is there a way to run it on Ubuntu 22.04.3 LTS?

Thanks for your response!

Thanks.

**Comment by hello-11** [comment]
@amir1m Do you still have the problem? If not, we will close it soon.
