### ISSUE TITLE
Graph rewriting question

### ISSUE THREAD

**Issue by Luis-xu** [NVIDIA/TensorRT-LLM#629]
Dear developer！
I'm wondering to understand the relationship between graph rewriting and computational graph optimization in tensorrtllm. Currently, only FuseAttentionWithBiasPass is provided in graph rewriting module. Will there be other patterns in the future?

Looking forward to getting relevant answers.

**Comment by Superjomn** [comment]
Hi,
In the context of TensorRT-LLM, there is a [graph_rewriting](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/graph-rewriting.md) module which is based on the TensorRT [INetworkDefintion](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Network.html).

Currently, there is no dedicated Graph or IR-like stuff in TensorRT-LLM, the so-called graph is the INetworkDefinition, which is the IR of TensorRT. Since TensorRT cannot optimize the topologies containing plugins, there is some need for graph rewriting on this level in TensorRT-LLM, the `graph_rewriting` module helps to fulfill such needs.

>  only FuseAttentionWithBiasPass is provided in graph rewriting module

Yes, you are right. Since the TensorRT INetworkDefinition is quite a low-level representation in TensorRT-LLM, only the topology modification of plugins across multiple Modules is necessary to use the graph rewriting. For other needs, either flag within a `Module.forward()`(like [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/layers/attention.py#L599)) or monkey patching (like we did in [quant.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/quantized/quant.py#L42)) is sufficient.

> Will there be other patterns in the future?

Of course, since the TensorRT INetworkDefinition is the lowest representation, which acts like some level of IR/Graph/Network in TensorRT-LLM, we will keep adding other patterns IF NEEDED.

**Comment by Luis-xu** [comment]
@Superjomn Thank you for your detailed explanation, I think I have a deeper understanding of the above two concepts. And，where can I learn more about computational graph optimization of TensorRT.

**Comment by Superjomn** [comment]
I think the [TensorRT INetworkDefinition](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Network.html) could be a good starting point, it helps to build a Network with ILayers. But concerning graph optimization, if I understand correctly, TensorRT performs such optimization like a black box. Although there are tons of patterns, I think the developer cannot access them.
@Luis-xu
