### ISSUE TITLE
Some questions about graph rewriting

### ISSUE THREAD

**Issue by Jayce0625** [NVIDIA/TensorRT-LLM#657]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/95926907/b85d81d2-cfe4-49ac-ae30-5ea4e56f57df)
How can I get the data, I haven't used FLayerInfoMemo.instance().create() and FLayerInfoMemo.instance().add() before this, so corresponding to the boxed part of the diagram, how can I get the FLayerInfo object I want?
Looking forward to your reply, thanks!

**Comment by Jayce0625** [comment]
My English is not very good. Please forgive me.
Doubtful, I went through tensort-llm, only the gpt_attention function is decorated by this record_signature decorator, that is, only when executing the gpt_attention function, it will execute the body of this decorator function, which in turn will execute the function in the FLayerScope context manager class. But in the match_and_rewrite function, we use get() to get the value first, but at this time gpt_attention is still further down, that is, we have not executed the FLayerInfoMemo.instance().add() in the __exit__ of FLayerScope, that is, we use get() to get the value. Do we get the data from get() at this point?

**Comment by Superjomn** [comment]
Hi,

Before answering your questions, let me illustrate the motivation of the `FLayerInfo` so that you can tell whether it is the right solution for your scenarios. It is used for patching the "graph_rewriting.py" for the creation/replacement of TensorRT plugins in Python. Unlike the built-in TensorRT Layers, in which we can retrieve the information necessary for analysis or recreation, the TensorRT plugins don't have a Python interface since the definition varies a lot and the argument data type might be unsupported by Python native. The `FLayerInfoMemo` is a singleton used to hold the latest cache of all the function calls (FlayerInfo) targeting the functions(wrappers of TensorRT layer/plugin) from functional.py, the cache is actually a map from a TensorRT-layer-name to a FLayerInfo instance.

The FLayerInfoMemo is a [singleton per-network](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/network.py#L60), so when doing graph rewriting, **the explicit creation is not needed**. It should record all the calls to the functions in functional.py once the function is decorated by [@gw.record_signature](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/functional.py#L3178). And all the operations from graph rewriting such as [replace_all_uses_with](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/functional.py#L511) will update the FLayerInfo cache as well.
