### ISSUE TITLE
Which version of TensorRT-LLM and tensorrtllm_backend support Mixtral?

### ISSUE THREAD

**Issue by RajdeepBorgohain** [NVIDIA/TensorRT-LLM#872]
Hi,
I have been working on Quantizing Mixtral using the TensorRT-LLM[v0.7.1]
1. Clone the TensorRT-LLM[v0.7.1] repo, build the docker container.
2. Build the engine using int8 quantization.
3. Load the model on the nvcr.io/nvidia/tritonserver:23.11-trtllm-python-py3 docker container, I have tried both 11 & 12 but none of them worked.

1. I have seen people use previous versions to match the TRT version, but that will not work as 0.7.1 has the support for Mixtral.
2. I have seen people swap the libs of the docker, but again I couldn't find the path from those libs to be coppied.

Related issues:
#815 #656 

https://github.com/triton-inference-server/tensorrtllm_backend/issues/194
https://github.com/triton-inference-server/tensorrtllm_backend/issues/213
https://github.com/triton-inference-server/tensorrtllm_backend/issues/194
https://github.com/NVIDIA/TensorRT-LLM/issues/583

Question to @byshiue, You have suggested rebuilding the engine. For my use case:
I will be using the TensorRT-LLM[v0.7.1] which version of tensorrtllm_backend and Tritonserver container I should use?

<img width="951" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/150957746/8a0e88b7-98cd-4c71-9134-995a02268242">

Question to @kaiyux, How to use the Tritonserver container to build the quantize and build the engine?
Please share some suggestions and reference
<img width="952" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/150957746/711c3b73-f4a8-45aa-a555-3bb899c2341f">

**Comment by Jensssen** [comment]
In order to have Tritonserver as well as tensorrt-llm for building the engine in one container, you could checkout https://github.com/triton-inference-server/tensorrtllm_backend/tree/v0.6.1 and use [Option 3](https://github.com/triton-inference-server/tensorrtllm_backend/tree/v0.6.1?tab=readme-ov-file#option-3-build-via-docker) to build the docker locally and then follow [this](https://github.com/triton-inference-server/tensorrtllm_backend/tree/v0.6.1?tab=readme-ov-file#option-3-build-via-docker) to build the engine within the tritonserver backend docker.

**Comment by RajdeepBorgohain** [comment]
Thanks @Jensssen , I will give it a try

**Comment by shixianc** [comment]
it seems tritonserver:24.01 works for me

**Comment by byshiue** [comment]
Mixtral is supported in latest version. Close this issue.
