### ISSUE TITLE
gptManagerBenchmark  has no argument for --max_num_sequences

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#950]
So this option is deleted. Do I still need to control the max concurrent requests?

Or the max_num_sequences is set the same as the build option max_batch_size? 

I notice, when the batch size is too large, the performance gets lower. 

1. why is that? Due to the swap in and swap out of inflight batching?
2. How can I get the best concurrency when running a model? by trying a lot of batches one by one?

**Comment by nekorobov** [comment]
Hi @sleepwalker2017 , maximum number of sequences is now purely determined by the batch size and the mode of the execution. E.g. when `enable_trt_overlap` is set, we use 2 "microbatches" and do ping-pong execution between them. In this case, maximum number of requests in the system is `2*max_batch_size`.

>I notice, when the batch size is too large, the performance gets lower.

Could you be more specific about this? Which configuration do you run? Which scheduling policy do you use? E.g. when using `max_utilization`, it could be that requests can't be scheduled due to the lack of KV cache and they get "paused" until more KV cache is available. In theory, performance of this could be as slow as if you were running the same amount of requests, but with lower batch size in more iterations. However, in practice, there are several overheads connected to the pausing and resuming of the requests.

>How can I get the best concurrency when running a model? by trying a lot of batches one by one?

The best performance might be achieved by maximizing the batch size without oversubscribing to the KV cache. Total usage of KV cache is sum of the sequence lengths over all active requests. Thus, it could be that you can fit more requests (achieve the best perf with larger batch size) if their average seq len is rather short, or fewer requests (achieve the best perf with smaller batch size) if their expected length is large. It fully depends on your model, HW, build and deploy settings. 

I hope that answers your questions :)

**Comment by lyc728** [comment]
> So this option is deleted. Do I still need to control the max concurrent requests?
> 
> Or the max_num_sequences is set the same as the build option max_batch_size?
> 
> I notice, when the batch size is too large, the performance gets lower.
> 
> 1. why is that? Due to the swap in and swap out of inflight batching?
> 2. How can I get the best concurrency when running a model? by trying a lot of batches one by one?

Hi, I conducted a multi-threaded concurrent request here, and found that triton added inflighting batch or V1 in the configuration, and the time was almost unchanged

https://github.com/NVIDIA/TensorRT-LLM/tree/v0.7.0/examples/qwen There is no In-flight Batching of the Support Matrix here,
and v0.7.1 is no In-flight Batching of the Support Matrix here
howerver https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/qwen is support the In-flight Batching, I wonder if this really works

please help me to fix the problem
